### ISSUE TITLE
Users with Az via PowerShell

### ISSUE THREAD

**Issue by mariuszdotnet** [jungho/k8s-bootcamp-ms#1]
Please update instructions for users with PS and Az.  Step 1 provisioning the cluster.

az aks create -g k8s-example -n test-cluster -c 2 -k 1.10.8 -l canadacentral

ERROR:
"An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you"

**Comment by jungho** [comment]
Updated documentation to provision the cluster.
